apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-nginx-ingress-trial.fullname" . }}
  annotations:
    {{- toYaml .Values.controller.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
